name       : topydo
version    : 0.12
release    : 1
source     :
    - https://github.com/bram85/topydo/archive/0.12.tar.gz : d723198e7ced9014d8692f561b1c9a07f2adb03352c6d4271e718b920424f5c4
license    : GPL-3.0
component  : office.notes
summary    : A powerful todo list application for the console, using the todo.txt format
description: |
    A powerful todo list application for the console, using the todo.txt format
rundeps  : 
    - python-arrow
    - python-pathtools
    - python-prompt-toolkit
    - python-six
    - python-watchdog
    - python-wcwidth
    - python3-urwid
build      : |
    %python3_setup
install    : |
    %python3_install
