name       : topydo
version    : 0.13
release    : 5
source     :
    - https://github.com/bram85/topydo/archive/0.13.tar.gz : 1d733c8a8584e4a21acda1bb89b2bd76a162dbef20152b02115b6fb12c475554
homepage   : https://github.com/bram85/topydo
license    : GPL-3.0-or-later
component  : office.notes
summary    : A powerful todo list application for the console, using the todo.txt format
description: |
    A powerful todo list application for the console, using the todo.txt format
rundeps    :
    - python-arrow
    - python-prompt-toolkit
    - python-watchdog
    - python3-urwid
build      : |
    %python3_setup
install    : |
    %python3_install
